baseURL = '/'
languageCode = 'en-us'
title = '🏠home'
theme = 'hugo-book'

[params]
  BookTheme = "auto" # light/dark mode auto switch
  BookSection = '*'
  BookSearch = false

[outputs]
  home = ["HTML", "RSS", "JSON"]