baseURL = 'http://docs.abhimanyu-g.github.io/'
languageCode = 'en-us'
title = 'Calicofx Documentation'
theme = 'hugo-book'

[params]
  BookTheme = "auto" # light/dark mode auto switch
[outputs]
  home = ["HTML", "RSS", "JSON"]